name: Trigger Reusable Workflow

# on:
#   workflow_dispatch: # Allows manual triggering of this workflow

workflow_dispatch:
    inputs:
      cluster_name:
        description: "Cluster name"
        required: true
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  call_reusable_workflow:
    name: Call Reusable Workflow
    uses: bn-ruturaj-patil/testing-workflow/.github/workflows/test_workflow.yaml@main
    with:
      cluster_name: ${{ inputs.cluster_name }}

