name: Trigger Reusable Workflow

on:
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  call_reusable_workflow:
    name: Call Reusable Workflow
    uses: bn-ruturaj-patil/testing-workflow/.github/workflows/test_workflow.yaml@main
    with:
      cluster_name: aks-test-nonprod
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
